services:
  api:
    # Constrói a imagem a partir do Dockerfile no diretório atual
    build: .
    # Define um nome para o contêiner para fácil identificação
    container_name: api_escola
    # Mapeia a porta 8000 do seu computador para a porta 8000 do contêiner
    ports:
      - "8000:8000"
    # Monta o diretório atual no diretório /app do contêiner.
    # Isso permite que as alterações no seu código local sejam refletidas
    # instantaneamente no contêiner, sem a necessidade de reconstruir a imagem.
    volumes:
      - .:/app